// Dados mockados para desenvolvimento e testes

// Função para gerar datas realistas (1-30 dias atrás)
const generateRandomDate = (daysAgo: number) => {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  return date
}

// Mock de vagas
export const mockJobs = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp Brasil',
    description: 'Buscamos um desenvolvedor frontend experiente para trabalhar com React, Next.js e TypeScript em projetos de grande escala.',
    salaryRange: 'R$ 15.000 - R$ 20.000',
    location: 'São Paulo, SP',
    remote: true,
    seniority: 'SENIOR',
    createdAt: generateRandomDate(2),
  },
  {
    id: '2',
    title: 'Full Stack Developer',
    company: 'Startup Inovadora',
    description: 'Oportunidade para desenvolvedor full stack com experiência em Node.js, React e banco de dados SQL.',
    salaryRange: 'R$ 12.000 - R$ 16.000',
    location: 'Remoto',
    remote: true,
    seniority: 'PLENO',
    createdAt: generateRandomDate(5),
  },
  {
    id: '3',
    title: 'Backend Developer',
    company: 'Empresa Fintech',
    description: 'Desenvolvedor backend para trabalhar com APIs, microserviços e arquitetura de sistemas escaláveis.',
    salaryRange: 'R$ 14.000 - R$ 18.000',
    location: 'Rio de Janeiro, RJ',
    remote: false,
    seniority: 'PLENO',
    createdAt: generateRandomDate(7),
  },
  {
    id: '4',
    title: 'Junior Frontend Developer',
    company: 'Agência Digital',
    description: 'Vaga para desenvolvedor júnior com conhecimento básico em HTML, CSS, JavaScript e desejo de aprender React.',
    salaryRange: 'R$ 4.000 - R$ 6.000',
    location: 'Belo Horizonte, MG',
    remote: false,
    seniority: 'JUNIOR',
    createdAt: generateRandomDate(10),
  },
  {
    id: '5',
    title: 'Tech Lead',
    company: 'Grande Empresa',
    description: 'Líder técnico para gerenciar equipe de desenvolvimento, definir arquitetura e melhores práticas.',
    salaryRange: 'R$ 25.000 - R$ 35.000',
    location: 'São Paulo, SP',
    remote: true,
    seniority: 'ESPECIALISTA',
    createdAt: generateRandomDate(14),
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'Cloud Solutions',
    description: 'Engenheiro DevOps para trabalhar com CI/CD, Docker, Kubernetes e infraestrutura como código.',
    salaryRange: 'R$ 18.000 - R$ 25.000',
    location: 'Remoto',
    remote: true,
    seniority: 'SENIOR',
    createdAt: generateRandomDate(18),
  },
  {
    id: '7',
    title: 'Product Manager',
    company: 'TechStart',
    description: 'Gerente de produto para liderar desenvolvimento de produtos digitais e definir roadmap estratégico.',
    salaryRange: 'R$ 16.000 - R$ 22.000',
    location: 'São Paulo, SP',
    remote: true,
    seniority: 'SENIOR',
    createdAt: generateRandomDate(1),
  },
  {
    id: '8',
    title: 'UX Designer',
    company: 'Design Studio',
    description: 'Designer UX para criar experiências incríveis em aplicações mobile e web.',
    salaryRange: 'R$ 8.000 - R$ 12.000',
    location: 'Remoto',
    remote: true,
    seniority: 'PLENO',
    createdAt: generateRandomDate(4),
  },
  {
    id: '9',
    title: 'Data Analyst',
    company: 'Analytics Corp',
    description: 'Analista de dados para trabalhar com SQL, Python e visualização de dados.',
    salaryRange: 'R$ 10.000 - R$ 14.000',
    location: 'Curitiba, PR',
    remote: false,
    seniority: 'PLENO',
    createdAt: generateRandomDate(6),
  },
  {
    id: '10',
    title: 'Marketing Manager',
    company: 'Growth Agency',
    description: 'Gerente de marketing para planejar e executar estratégias de crescimento digital.',
    salaryRange: 'R$ 12.000 - R$ 18.000',
    location: 'São Paulo, SP',
    remote: true,
    seniority: 'SENIOR',
    createdAt: generateRandomDate(8),
  },
  {
    id: '11',
    title: 'Junior Backend Developer',
    company: 'Software House',
    description: 'Desenvolvedor backend júnior para trabalhar com Python e Django.',
    salaryRange: 'R$ 5.000 - R$ 7.000',
    location: 'Porto Alegre, RS',
    remote: false,
    seniority: 'JUNIOR',
    createdAt: generateRandomDate(11),
  },
  {
    id: '12',
    title: 'HR Business Partner',
    company: 'Big Company',
    description: 'Parceiro de RH para atuar como consultor interno em áreas de negócio.',
    salaryRange: 'R$ 9.000 - R$ 13.000',
    location: 'Rio de Janeiro, RJ',
    remote: false,
    seniority: 'PLENO',
    createdAt: generateRandomDate(13),
  },
  {
    id: '13',
    title: 'Sales Representative',
    company: 'Sales Force',
    description: 'Representante de vendas para prospectar e fechar contratos B2B.',
    salaryRange: 'R$ 6.000 - R$ 10.000 + comissão',
    location: 'São Paulo, SP',
    remote: true,
    seniority: 'PLENO',
    createdAt: generateRandomDate(16),
  },
  {
    id: '14',
    title: 'Senior Data Scientist',
    company: 'AI Solutions',
    description: 'Cientista de dados sênior para desenvolver modelos de machine learning.',
    salaryRange: 'R$ 20.000 - R$ 30.000',
    location: 'Remoto',
    remote: true,
    seniority: 'ESPECIALISTA',
    createdAt: generateRandomDate(19),
  },
  {
    id: '15',
    title: 'Mobile Developer',
    company: 'App Factory',
    description: 'Desenvolvedor mobile para criar apps nativos iOS e Android.',
    salaryRange: 'R$ 11.000 - R$ 16.000',
    location: 'Belo Horizonte, MG',
    remote: true,
    seniority: 'PLENO',
    createdAt: generateRandomDate(21),
  },
  {
    id: '16',
    title: 'QA Engineer',
    company: 'Quality First',
    description: 'Engenheiro de QA para garantir qualidade de software com testes automatizados.',
    salaryRange: 'R$ 8.000 - R$ 12.000',
    location: 'Remoto',
    remote: true,
    seniority: 'PLENO',
    createdAt: generateRandomDate(23),
  },
  {
    id: '17',
    title: 'Cloud Architect',
    company: 'Cloud Masters',
    description: 'Arquiteto de cloud para projetar infraestrutura em AWS/Azure/GCP.',
    salaryRange: 'R$ 22.000 - R$ 32.000',
    location: 'São Paulo, SP',
    remote: true,
    seniority: 'ESPECIALISTA',
    createdAt: generateRandomDate(25),
  },
  {
    id: '18',
    title: 'Junior Marketing Analyst',
    company: 'Digital Agency',
    description: 'Analista de marketing júnior para apoiar campanhas digitais.',
    salaryRange: 'R$ 3.500 - R$ 5.000',
    location: 'Rio de Janeiro, RJ',
    remote: false,
    seniority: 'JUNIOR',
    createdAt: generateRandomDate(27),
  },
  {
    id: '19',
    title: 'Cybersecurity Analyst',
    company: 'Secure Tech',
    description: 'Analista de segurança para proteger sistemas e dados corporativos.',
    salaryRange: 'R$ 14.000 - R$ 20.000',
    location: 'Remoto',
    remote: true,
    seniority: 'SENIOR',
    createdAt: generateRandomDate(28),
  },
  {
    id: '20',
    title: 'Scrum Master',
    company: 'Agile Corp',
    description: 'Scrum Master para facilitar processos ágeis e cerimônias de time.',
    salaryRange: 'R$ 10.000 - R$ 15.000',
    location: 'São Paulo, SP',
    remote: true,
    seniority: 'PLENO',
    createdAt: generateRandomDate(29),
  },
]

// Mock de usuário e perfil
export const mockUser = {
  id: '1',
  email: 'usuario@exemplo.com',
  name: 'João Silva',
  avatar: null,
  linkedinUrl: 'https://linkedin.com/in/joaosilva',
  createdAt: new Date('2024-01-01'),
}

export const mockProfile = {
  id: '1',
  userId: '1',
  headline: 'Desenvolvedor Full Stack | React | Node.js',
  summary: 'Desenvolvedor full stack com 5 anos de experiência em desenvolvimento de aplicações web. Paixonado por criar soluções inovadoras e trabalhar em equipe.',
  phone: '(11) 98765-4321',
  location: 'São Paulo, SP',
  createdAt: new Date('2024-01-01'),
  experiences: [
    {
      id: '1',
      profileId: '1',
      company: 'Tech Company',
      role: 'Senior Developer',
      startDate: new Date('2022-01-01'),
      endDate: null,
      description: 'Liderança de equipe de desenvolvimento, arquitetura de sistemas e implementação de novas features.',
    },
    {
      id: '2',
      profileId: '1',
      company: 'Startup XYZ',
      role: 'Full Stack Developer',
      startDate: new Date('2020-01-01'),
      endDate: new Date('2021-12-31'),
      description: 'Desenvolvimento de aplicações web usando React, Node.js e PostgreSQL.',
    },
  ],
  skills: [
    { id: '1', profileId: '1', name: 'React', level: 'SENIOR' },
    { id: '2', profileId: '1', name: 'TypeScript', level: 'SENIOR' },
    { id: '3', profileId: '1', name: 'Node.js', level: 'PLENO' },
    { id: '4', profileId: '1', name: 'PostgreSQL', level: 'PLENO' },
    { id: '5', profileId: '1', name: 'Docker', level: 'JUNIOR' },
  ],
  education: [
    {
      id: '1',
      profileId: '1',
      institution: 'Universidade de São Paulo',
      course: 'Ciência da Computação',
      year: 2019,
      description: 'Bacharelado em Ciência da Computação',
    },
  ],
}

// Mock de candidaturas (Kanban)
export const mockJobApplications = [
  {
    id: '1',
    userId: '1',
    jobId: '1',
    status: 'INTERVIEW',
    notes: 'Entrevista técnica agendada para próxima terça-feira',
    appliedAt: generateRandomDate(3),
  },
  {
    id: '2',
    userId: '1',
    jobId: '2',
    status: 'APPLIED',
    notes: 'Currículo enviado, aguardando retorno',
    appliedAt: generateRandomDate(7),
  },
  {
    id: '3',
    userId: '1',
    jobId: '3',
    status: 'INTEREST',
    notes: 'Interessante, preciso preparar o currículo',
    appliedAt: generateRandomDate(10),
  },
  {
    id: '4',
    userId: '1',
    jobId: '4',
    status: 'OFFER',
    notes: 'Proposta recebida, analisando',
    appliedAt: generateRandomDate(15),
  },
  {
    id: '5',
    userId: '1',
    jobId: '5',
    status: 'FINISHED',
    notes: 'Processo concluído, não aceitaram',
    appliedAt: generateRandomDate(25),
  },
]

// Mock de métricas do dashboard
export const mockDashboardMetrics = {
  savedJobs: 12,
  activeApplications: 5,
  scheduledInterviews: 2,
  responseRate: 35,
}